// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvQQ_y-waL0WLze3c-G1LENZSM40IW84',
    appId: '1:721186721049:web:27c10318efc55136480988',
    messagingSenderId: '721186721049',
    projectId: 'ecommerceapp-a1018',
    authDomain: 'ecommerceapp-a1018.firebaseapp.com',
    storageBucket: 'ecommerceapp-a1018.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdCA7toczi9vy_ERIxbuoEqGInKYVOo0',
    appId: '1:721186721049:android:9cb72b6d39b6dcf5480988',
    messagingSenderId: '721186721049',
    projectId: 'ecommerceapp-a1018',
    storageBucket: 'ecommerceapp-a1018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-mNMJZo5Vh03AK5uar2GYjNr242HOMg',
    appId: '1:721186721049:ios:5f649cd1275c3a6d480988',
    messagingSenderId: '721186721049',
    projectId: 'ecommerceapp-a1018',
    storageBucket: 'ecommerceapp-a1018.firebasestorage.app',
    iosClientId: '721186721049-pciq1gqveorb53n4379fpm4mfluqgcci.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceDemo',
  );
}
